"""empty message

Revision ID: b7572a37641c
Revises: 73030ae737db
Create Date: 2021-06-08 18:21:04.323306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7572a37641c'
down_revision = '73030ae737db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consumer_uses', sa.Column('weight', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('consumer_uses', 'weight')
    # ### end Alembic commands ###
