"""empty message

Revision ID: b3e37c41dbb5
Revises: ffdc0a98111c
Create Date: 2021-06-03 19:42:41.342085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3e37c41dbb5'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('admin_email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('statement', sa.Text(), nullable=True),
    sa.Column('warehouse_location', sa.String(), nullable=False),
    sa.Column('products_sold', sa.Integer(), nullable=False),
    sa.Column('carbon_goal', sa.Float(), nullable=True),
    sa.Column('carbon_goal_date', sa.DateTime(), nullable=True),
    sa.Column('transparency_score', sa.Integer(), nullable=True),
    sa.Column('c_footprint_mt', sa.Float(), nullable=True),
    sa.Column('signup_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admin_email'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('companies')
    # ### end Alembic commands ###
