"""empty message

Revision ID: 73030ae737db
Revises: 83b55759576d
Create Date: 2021-06-08 18:20:26.091789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73030ae737db'
down_revision = '83b55759576d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('consumer_uses', 'weight')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consumer_uses', sa.Column('weight', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
