"""empty message

Revision ID: 406918edc614
Revises: 351a2a2ae318
Create Date: 2021-06-08 13:52:55.686660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '406918edc614'
down_revision = '351a2a2ae318'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('admin_email', sa.String(length=255), nullable=False))
    op.add_column('companies', sa.Column('c_footprint_mt', sa.Float(), nullable=True))
    op.add_column('companies', sa.Column('carbon_goal', sa.Float(), nullable=True))
    op.add_column('companies', sa.Column('carbon_goal_date', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('hashed_password', sa.String(length=255), nullable=False))
    op.add_column('companies', sa.Column('logo_url', sa.String(length=255), nullable=True))
    op.add_column('companies', sa.Column('name', sa.String(length=40), nullable=False))
    op.add_column('companies', sa.Column('products_sold', sa.Integer(), nullable=False))
    op.add_column('companies', sa.Column('signup_date', sa.DateTime(), nullable=True))
    op.add_column('companies', sa.Column('statement', sa.Text(), nullable=True))
    op.add_column('companies', sa.Column('transparency_score', sa.Integer(), nullable=True))
    op.add_column('companies', sa.Column('warehouse_location', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'companies', ['admin_email'])
    op.create_unique_constraint(None, 'companies', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'companies', type_='unique')
    op.drop_constraint(None, 'companies', type_='unique')
    op.drop_column('companies', 'warehouse_location')
    op.drop_column('companies', 'transparency_score')
    op.drop_column('companies', 'statement')
    op.drop_column('companies', 'signup_date')
    op.drop_column('companies', 'products_sold')
    op.drop_column('companies', 'name')
    op.drop_column('companies', 'logo_url')
    op.drop_column('companies', 'hashed_password')
    op.drop_column('companies', 'carbon_goal_date')
    op.drop_column('companies', 'carbon_goal')
    op.drop_column('companies', 'c_footprint_mt')
    op.drop_column('companies', 'admin_email')
    # ### end Alembic commands ###
