"""empty message

Revision ID: 20643d893e48
Revises: da2aab9a72dc
Create Date: 2021-06-13 19:18:38.216302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20643d893e48'
down_revision = 'da2aab9a72dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('base_users', sa.Column('company_id', sa.Integer(), nullable=True))
    op.add_column('base_users', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'base_users', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'base_users', 'companies', ['company_id'], ['id'])
    op.drop_constraint('companies_base_user_id_fkey', 'companies', type_='foreignkey')
    op.drop_column('companies', 'base_user_id')
    op.drop_constraint('users_base_user_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'base_user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('base_user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_base_user_id_fkey', 'users', 'base_users', ['base_user_id'], ['id'])
    op.add_column('companies', sa.Column('base_user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('companies_base_user_id_fkey', 'companies', 'base_users', ['base_user_id'], ['id'])
    op.drop_constraint(None, 'base_users', type_='foreignkey')
    op.drop_constraint(None, 'base_users', type_='foreignkey')
    op.drop_column('base_users', 'user_id')
    op.drop_column('base_users', 'company_id')
    # ### end Alembic commands ###
