"""empty message

Revision ID: 918222c64c8e
Revises: b7572a37641c
Create Date: 2021-06-08 18:56:25.993543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '918222c64c8e'
down_revision = 'b7572a37641c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('photo_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'photo_url')
    # ### end Alembic commands ###
