"""empty message

Revision ID: ed0e74ef40e3
Revises: f13f87a7af13
Create Date: 2021-06-08 17:18:11.416746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed0e74ef40e3'
down_revision = 'f13f87a7af13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('country_grids', sa.Column('electricity', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('country_grids', 'electricity')
    # ### end Alembic commands ###
