"""empty message

Revision ID: f13f87a7af13
Revises: 406918edc614
Create Date: 2021-06-08 17:11:25.847841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f13f87a7af13'
down_revision = '406918edc614'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('material', sa.String(), nullable=True),
    sa.Column('weight_g', sa.Float(), nullable=True),
    sa.Column('total_used', sa.Integer(), nullable=True),
    sa.Column('waste_recycled', sa.Boolean(), nullable=True),
    sa.Column('material_recycled_percent', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consumer_uses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('country_grids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manufacturing_processes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transport_modes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('factories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('country_grid_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['country_grid_id'], ['country_grids.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('product_category', sa.String(), nullable=True),
    sa.Column('manufacturing_process_id', sa.Integer(), nullable=True),
    sa.Column('product_weight_g', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('factory_id', sa.Integer(), nullable=False),
    sa.Column('package_weight_g', sa.Float(), nullable=True),
    sa.Column('transport_mode_id', sa.Integer(), nullable=True),
    sa.Column('number_of_cycles', sa.Integer(), nullable=True),
    sa.Column('returnable', sa.Boolean(), nullable=True),
    sa.Column('product_returned_percent', sa.Float(), nullable=True),
    sa.Column('product_recycled_percent', sa.Float(), nullable=True),
    sa.Column('carbon_footprint_kg', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['factory_id'], ['factories.id'], ),
    sa.ForeignKeyConstraint(['manufacturing_process_id'], ['manufacturing_processes.id'], ),
    sa.ForeignKeyConstraint(['transport_mode_id'], ['factories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('component_table',
    sa.Column('component_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], )
    )
    op.create_table('use_table',
    sa.Column('consumer_use_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['consumer_use_id'], ['consumer_uses.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('use_table')
    op.drop_table('component_table')
    op.drop_table('products')
    op.drop_table('factories')
    op.drop_table('transport_modes')
    op.drop_table('manufacturing_processes')
    op.drop_table('country_grids')
    op.drop_table('consumer_uses')
    op.drop_table('components')
    # ### end Alembic commands ###
